"""
ISI and CV Statistics Comparison Plot
======================================

This script loads and visualizes ISI/CV data from multiple MVC levels (generated by
extract_isi_and_cv_per_ramps.py) and compares them against experimental data.

Usage:
------
python plot_isi_cv_comparison.py --muscle VLVM --mvc-levels 5 15 30
"""

import os

os.environ["MPLBACKEND"] = "Agg"
if "DISPLAY" in os.environ:
    del os.environ["DISPLAY"]

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scienceplots  # noqa
import seaborn as sns
from matplotlib.patches import Polygon
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
from scipy.spatial import ConvexHull

##############################################################################
# Configure Matplotlib Style
# ---------------------------
# Match the styling from model_adjust.py for consistency

plt.style.use(["science", "nature"])
sns.set_context("paper", font_scale=2)

# Disable LaTeX rendering
plt.rcParams["text.usetex"] = False
plt.rcParams["figure.dpi"] = 300
plt.rcParams["savefig.dpi"] = 300
plt.rcParams["figure.figsize"] = (8, 6)

# Keep text editable in SVG/PDF exports
plt.rcParams["svg.fonttype"] = "none"
plt.rcParams["pdf.fonttype"] = 42

# Set font
plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = ["Liberation Sans", "Roboto", "DejaVu Sans"]

# Remove top and right spines
plt.rcParams["axes.spines.top"] = False
plt.rcParams["axes.spines.right"] = False
plt.rcParams["xtick.top"] = False
plt.rcParams["ytick.right"] = False

# Make ticks and axis lines thicker
plt.rcParams["axes.linewidth"] = 2.0
plt.rcParams["xtick.major.width"] = 2.0
plt.rcParams["ytick.major.width"] = 2.0

# Remove minor ticks
plt.rcParams["xtick.minor.visible"] = False
plt.rcParams["ytick.minor.visible"] = False

# Adjust subplot spacing
plt.rcParams["figure.subplot.left"] = 0.2
plt.rcParams["figure.subplot.bottom"] = 0.15

##############################################################################
# CONFIGURATION
# -------------

# Muscle type to analyze
MUSCLE_TYPE = "VLVM"  # Options: "VLVM", "TA", "FDI"

# MVC levels to include in comparison (can be any number of levels)
MVC_LEVELS = [5, 15, 30]

# Path to results directory
RESULTS_PATH = Path("./results")

# Experimental data colors (all gray)
EXP_COLORS = {"VM": "#808080", "VL": "#808080", "TA": "#808080", "FDI": "#808080"}

# Available marker styles (will cycle through these)
AVAILABLE_MARKERS = ["o", "s", "^", "v", "D", "p", "*", "h", "<", ">", "d", "P", "X"]


def generate_mvc_markers(mvc_levels):
    """
    Generate marker mappings for any number of MVC levels.

    Colors are handled by the viridis colormap based on recruitment order.
    This function only assigns distinct marker shapes for each MVC level.

    Parameters
    ----------
    mvc_levels : list of int
        List of MVC levels (e.g., [5, 10, 15, 30, 50])

    Returns
    -------
    dict
        mvc_markers - dictionary mapping mvc_level to marker shape
    """
    mvc_markers = {}

    for i, mvc in enumerate(sorted(mvc_levels)):
        # Assign marker (cycle through available markers)
        mvc_markers[mvc] = AVAILABLE_MARKERS[i % len(AVAILABLE_MARKERS)]

    return mvc_markers

##############################################################################
# Data Loading Functions
# -----------------------


def load_simulation_data(results_path, muscle_type, mvc_levels, study_prefix=""):
    """
    Load ISI/CV data for multiple MVC levels from CSV files.

    Parameters
    ----------
    results_path : Path
        Path to results directory containing CSV files.
    muscle_type : str
        Muscle type identifier (e.g., "VLVM", "TA", "FDI").
    mvc_levels : list of int
        List of MVC levels to load (e.g., [5, 15, 30]).
    study_prefix : str, optional
        Study prefix for file naming (e.g., "VLVM_")

    Returns
    -------
    dict
        Dictionary mapping {mvc_level: DataFrame} with columns:
        - MU_ID: Motor unit identifier
        - mean_firing_rate_Hz: Mean firing rate in Hz
        - CV_ISI: Coefficient of variation of inter-spike intervals
    """
    data_dict = {}

    for mvc in mvc_levels:
        file_path = results_path / f"{study_prefix}isi_cv_data_{muscle_type}_{mvc}.csv"
        if file_path.exists():
            df = pd.read_csv(file_path)
            data_dict[mvc] = df
            print(f"✓ Loaded {len(df)} motor units for {mvc}% MVC from {file_path.name}")
        else:
            print(f"✗ File not found: {file_path}")
            print(f"  Expected: {file_path.name}")

    return data_dict


def load_experimental_data(csv_path):
    """
    Load experimental ISI statistics from CSV file.

    Parameters
    ----------
    csv_path : Path
        Path to ISI_statistics.csv file.

    Returns
    -------
    pd.DataFrame
        Experimental data with columns including:
        - Muscle: Muscle identifier
        - Force Level: Force level (%)
        - FR mean: Mean firing rate (pps)
        - ISI CV: Coefficient of variation
    """
    if csv_path.exists():
        df = pd.read_csv(csv_path)
        print(f"✓ Loaded experimental data: {len(df)} records")
        return df
    else:
        print(f"✗ Experimental data file not found: {csv_path}")
        return None


##############################################################################
# Plotting Function
# -----------------


def plot_cv_vs_fr_comparison(
    sim_data_dict, exp_data, muscle_type, mvc_markers, exp_colors
):
    """
    Create CV vs FR plot comparing simulated MVC levels with experimental data.

    This function creates a publication-ready scatter plot showing the relationship
    between coefficient of variation (CV) and mean firing rate. Experimental data
    is shown with convex hulls and scatter markers, while simulated data for each
    MVC level is shown with distinct colors based on recruitment order.

    Parameters
    ----------
    sim_data_dict : dict
        Dictionary {mvc_level: DataFrame} with simulation data.
    exp_data : pd.DataFrame
        Experimental ISI statistics.
    muscle_type : str
        Muscle type being analyzed.
    mvc_markers : dict
        Marker styles for each MVC level {mvc_level: marker}.
    exp_colors : dict
        Colors for experimental muscles {muscle: color}.

    Returns
    -------
    tuple
        (fig, ax) matplotlib figure and axis objects.
    """
    fig, ax = plt.subplots(figsize=(8, 6))

    # 1. Plot experimental data (convex hulls + scatter)
    if exp_data is not None:
        muscles = exp_data["Muscle"].unique()
        for muscle in muscles:
            # Skip FDI data
            if muscle == "FDI":
                continue

            muscle_data = exp_data[exp_data["Muscle"] == muscle]
            cv_data = muscle_data["ISI CV"].values
            fr_data = muscle_data["FR mean"].values

            # Draw convex hull for experimental data
            if len(cv_data) > 2:
                points = np.column_stack([cv_data, fr_data])
                try:
                    hull = ConvexHull(points)
                    hull_points = points[hull.vertices]
                    polygon = Polygon(
                        hull_points,
                        facecolor=exp_colors.get(muscle, "#000000"),
                        alpha=0.25,
                        edgecolor=exp_colors.get(muscle, "#000000"),
                        linewidth=1.5,
                        linestyle="-",
                        zorder=0,
                    )
                    ax.add_patch(polygon)
                except Exception:
                    # Skip if convex hull cannot be computed
                    pass

            # Scatter points for experimental data (no label for legend)
            ax.scatter(
                cv_data,
                fr_data,
                s=20,
                alpha=1.0,
                color=exp_colors.get(muscle, "#000000"),
                edgecolors="white",
                linewidth=0.5,
                marker="x",
                zorder=1,
            )

    # 2. Plot simulated data for each MVC level (colored by recruitment order)
    # Track global min/max recruitment order for consistent colorbar
    all_recruitment_orders = []

    for mvc_level in sorted(sim_data_dict.keys()):
        df = sim_data_dict[mvc_level]

        # Extract recruitment order from MU_ID (assuming MU_ID = recruitment order)
        # If MU_ID doesn't exist, create from index
        if "MU_ID" in df.columns:
            recruitment_order = df["MU_ID"].values
        else:
            recruitment_order = np.arange(len(df))

        all_recruitment_orders.extend(recruitment_order)

        # Normalize recruitment order to [0, 1] for colormap
        norm_recruitment = (recruitment_order - recruitment_order.min()) / (
            recruitment_order.max() - recruitment_order.min() + 1e-10
        )

        # Use rainbow colormap to color by recruitment order
        colors = plt.cm.rainbow(norm_recruitment)

        # Plot with recruitment order coloring and MVC-specific marker
        ax.scatter(
            df["CV_ISI"],
            df["mean_firing_rate_Hz"],
            s=50,
            alpha=0.8,
            c=colors,
            label=f"{mvc_level}%",
            edgecolors="black",
            linewidth=0.6,
            marker=mvc_markers.get(mvc_level, "o"),  # Use MVC-specific marker
            zorder=2,
        )

    # Add colorbar for recruitment order
    if all_recruitment_orders:
        min_recruitment = int(np.min(all_recruitment_orders))
        max_recruitment = int(np.max(all_recruitment_orders))

        # Create ScalarMappable for colorbar
        norm = Normalize(vmin=min_recruitment, vmax=max_recruitment)
        sm = ScalarMappable(cmap="rainbow", norm=norm)
        sm.set_array([])

        # Add colorbar
        cbar = plt.colorbar(sm, ax=ax, pad=0.02, aspect=30)
        cbar.set_label(
            "Recruitment Order (MU #)", fontsize=10, rotation=270, labelpad=20
        )
        cbar.ax.tick_params(labelsize=9)

    # 3. Format plot
    ax.set_xlabel("Coefficient of Variation (CV)", fontsize=12)
    ax.set_ylabel("Mean Firing Rate (pps)", fontsize=12)
    ax.set_xlim(0, 0.5)
    ax.set_ylim(4, 25)
    ax.set_title(f"ISI Statistics Comparison - {muscle_type}", fontsize=14)
    ax.tick_params(axis="both", labelsize=10)
    ax.legend(frameon=False, fontsize=9, loc="upper left")
    sns.despine(ax=ax, offset=10, trim=True)

    return fig, ax


##############################################################################
# Main Execution
# --------------


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(
        description="Plot ISI/CV comparison for multiple MVC levels"
    )
    parser.add_argument(
        "--muscle",
        type=str,
        default=MUSCLE_TYPE,
        help=f"Muscle type (default: {MUSCLE_TYPE})",
    )
    parser.add_argument(
        "--mvc-levels",
        type=int,
        nargs="+",
        default=MVC_LEVELS,
        help=f"MVC levels to plot (default: {MVC_LEVELS})",
    )
    parser.add_argument(
        "--results-path",
        type=Path,
        default=RESULTS_PATH,
        help=f"Path to results directory (default: {RESULTS_PATH})",
    )
    parser.add_argument(
        "--output-format",
        type=str,
        default="jpg",
        choices=["jpg", "png", "svg", "pdf"],
        help="Output format for figures (default: jpg)",
    )
    parser.add_argument(
        "--study-prefix",
        type=str,
        default="",
        help="Study prefix for file naming (default: none)",
    )

    args = parser.parse_args()

    print("=" * 70)
    print("ISI/CV Comparison Plot")
    print("=" * 70)
    print(f"  Muscle: {args.muscle}")
    print(f"  MVC Levels: {args.mvc_levels}")
    print(f"  Output Format: {args.output_format.upper()}")

    # Load simulation data
    print("\n📂 Loading simulation data...")
    sim_data = load_simulation_data(
        args.results_path, args.muscle, args.mvc_levels, args.study_prefix
    )

    if not sim_data:
        print(
            "\n❌ No simulation data found. Please run extract_isi_and_cv_per_ramps.py first."
        )
        exit(1)

    # Load experimental data
    print("\n📂 Loading experimental data...")
    exp_csv_path = Path(__file__).parent / "ISI_statistics.csv"
    exp_data = load_experimental_data(exp_csv_path)

    # Generate markers for MVC levels (colors are based on recruitment order)
    mvc_markers = generate_mvc_markers(args.mvc_levels)
    print(f"\n🎨 Generated {len(args.mvc_levels)} distinct marker shapes")

    # Create comparison plot
    print("\n📊 Creating comparison plot...")
    fig, ax = plot_cv_vs_fr_comparison(
        sim_data, exp_data, args.muscle, mvc_markers, EXP_COLORS
    )

    # Save figure with specified format
    output_file = (
        args.results_path
        / f"{args.study_prefix}isi_cv_comparison_{args.muscle}.{args.output_format}"
    )
    plt.tight_layout()

    # Set quality based on format
    if args.output_format in ["jpg", "jpeg"]:
        plt.savefig(output_file, dpi=300, bbox_inches="tight", pil_kwargs={"quality": 95})
    else:
        plt.savefig(output_file, dpi=300, bbox_inches="tight", transparent=True)

    print(f"\n✅ Plot saved to: {output_file}")

    # Print summary statistics
    print("\n" + "=" * 70)
    print("📊 SUMMARY STATISTICS")
    print("=" * 70)

    for mvc_level in sorted(sim_data.keys()):
        df = sim_data[mvc_level]
        print(f"\n{mvc_level}% MVC ({args.muscle}):")
        print(f"  Motor units (N):      {len(df)}")
        print(
            f"  Mean firing rate:     {df['mean_firing_rate_Hz'].mean():.2f} ± {df['mean_firing_rate_Hz'].std():.2f} Hz"
        )
        print(
            f"  Mean CV:              {df['CV_ISI'].mean():.3f} ± {df['CV_ISI'].std():.3f}"
        )
        print(
            f"  FR range:             {df['mean_firing_rate_Hz'].min():.2f} - {df['mean_firing_rate_Hz'].max():.2f} Hz"
        )
        print(
            f"  CV range:             {df['CV_ISI'].min():.3f} - {df['CV_ISI'].max():.3f}"
        )

    print("\n" + "=" * 70)
    print("✅ Analysis complete!")
    print("=" * 70)


if __name__ == "__main__":
    main()
