name: publish-docs

on:
  push:
    branches:
    - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libegl1-mesa-dev
        sudo apt-get update && sudo apt-get install infiniband-diags ibverbs-utils libibverbs-dev libfabric1 libfabric-dev libpsm2-dev -y
        sudo apt-get install openmpi-bin openmpi-common libopenmpi-dev libgtk2.0-dev
        sudo apt-get install librdmacm-dev libpsm2-dev
        python -m pip install --upgrade pip
        python -m pip install uv
        uv sync --group docs

    - name: Build the docs
      run: |
        source .venv/bin/activate
        python -c "from myogen.utils import setup_myogen; setup_myogen()"
        python -c "import myogen.simulator"
        cd docs
        make clean
        make html
        cd ..

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
